### ISSUE TITLE
NPM Module problem

### ISSUE THREAD

**Issue by antoniobrandao** [denar90/backbone.marionette-plupload-module#5]
This module is in NPM, but with instructions to be built with Bower. 

https://www.npmjs.com/package/backbone.marionette-plupload-module

Why? If it is in NPM, which is a package manager, would make more sense to make it the NPM way, not the Bower way, which is a different another package manager, and a different ecosystem.

You can add a NPM script to the package.json to make it build the NPM way.

Then let another, bower-like version be in the bower ecosystem.

It's a bit confusing to install a NPM module with instructions to be built for another package manager.

A "main" property can also be added in the package.json to specify which is the entry .js file (from ./dist in this case) to be loaded by loaders.

Just a suggestion!

**Comment by denar90** [comment]
It makes sense. Do you want to make pull request?
